additionalArguments:
# DNS Challenge
# ---
# Cloudflare Example:
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
#  - --certificatesresolvers.cloudflare.acme.email=your-email@example.com
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
#  - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json

service:
  loadBalancerIP: "10.0.5.231"

certificatesResolvers:
  cloudflare:
    acme:
      storage: "/ssl-certs/acme-cloudflare.json"
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "1.1.1.1"

ports:
  websecure:
    tls:
      certResolver: cloudflare
#  web:
#    redirectTo:
#      port: websecure

logs:
  general:
    level: DEBUG

env:
   #- name: CF_API_EMAIL
   #  valueFrom:
   #    secretKeyRef:
   #      key: email
   #      name: cloudflaresecrets
   #- name: CF_API_KEY
   #  valueFrom:
   #    secretKeyRef:
   #      key: apikey
   #      name: cloudflaresecrets
    - name: CLOUDFLARE_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: apikey
          name: cloudflaresecrets
    - name: CLOUDFLARE_ZONE_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: apikey
          name: cloudflaresecrets

serviceAccount:
  name: "traefik"

ingressRoute:
  dashboard:
    enabled: true

persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.37
      command: ["sh", "-c", "chown 65532:65532 /ssl-certs/*; chmod -Rv 600 /ssl-certs/*; touch /ssl-certs/acme-cloudflare.json; chmod -Rv 600 /ssl-certs/acme-cloudflare.json"]
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

ingressClass:
  enabled: true
  isDefaultClass: true